// constants.js
export const STAGES = [
  { id: "P1", dept: "Planner", label: "Communication by Planner", ref: "PO" },
  { id: "P2", dept: "Sales", label: "Order Acknowledgement", ref: "PO" },
  { id: "P3", dept: "Sales", label: "Client Approval (OA)", ref: "OA" },
  { id: "P4", dept: "Sales", label: "SOC Entry", ref: "PO" },
  { id: "P5", dept: "Sales", label: "SOT Entry", ref: "PO" },
  { id: "P6", dept: "Planner", label: "*Internal KO-1 (In. Commu+Days)", ref: "P1" },
  { id: "P7", dept: "Design", label: "Adv. Material to Purchase", ref: "P6" },
  { id: "P8", dept: "Sales", label: "*External KO-2 (Int KO+Days)", ref: "P6" },
  { id: "P9", dept: "Sales", label: "Proforma Invoice", ref: "OA" },
  { id: "P10", dept: "Finance & Sales", label: "ABG Draft Approval", ref: "P1" },
  { id: "P11", dept: "Finance", label: "BG Submission", ref: "P10" },
  { id: "P12", dept: "Design", label: "Drawing Commitment Date", ref: "P6" },
  { id: "P13", dept: "QC & Testing", label: "QAP Preparation", ref: "P8" },
  { id: "P14", dept: "Sales", label: "Advance Payment", ref: "P11" },
  { id: "P15", dept: "Sales", label: "Drawing Approval", ref: "P12" },
  { id: "P16", dept: "Sales", label: "MFC", ref: "P15" },
  { id: "P17", dept: "Planner", label: "Launch Meeting", ref: "MFC" },
  { id: "P18", dept: "Design", label: "BOM Release", ref: "MFC" },
  { id: "P19", dept: "Purchase", label: "LV Winding Kit Commit", ref: "P18" },
  { id: "P20", dept: "Purchase", label: "HV Winding Kit Commit", ref: "P18" },
  { id: "P21", dept: "Purchase", label: "CA Kit Commitment", ref: "P18" },
  { id: "P22", dept: "Purchase", label: "CCA Kit Commitment", ref: "P18" },
  { id: "P23", dept: "Purchase", label: "Tank Commitment", ref: "P18" },
  { id: "P24", dept: "Purchase", label: "Finishing Kit Commit", ref: "P18" },
  { id: "P25", dept: "Testing", label: "Final Testing Internal", ref: "P21" },
  { id: "P26", dept: "Testing", label: "Customer FAT", ref: "P25" },
  { id: "P27", dept: "Quality", label: "Compliance", ref: "P26" },
  { id: "P28", dept: "Sales", label: "MDCC", ref: "P27" },
  { id: "P29", dept: "QA", label: "Internal / Final DI", ref: "P27" },
  { id: "P30", dept: "Sales", label: "Payment Received", ref: "P28" },
  { id: "P31", dept: "Dispatch", label: "Ready for Dispatch", ref: "P28" },
  { id: "P32", dept: "Finance", label: "Actual Dispatch / Billing", ref: "P31" },
  { id: "P33", dept: "Planning", label: "Ex-Works", ref: "P32" }
];

export const DEPT_COLORS = {
  "Planner": "#2563eb",
  "Sales": "#059669",
  "Design": "#7c3aed",
  "Finance": "#d97706",
  "Finance & Sales": "#d97706",
  "Purchase": "#dc2626",
  "Testing": "#0891b2",
  "QC & Testing": "#0891b2",
  "Quality": "#65a30d",
  "QA": "#65a30d",
  "Dispatch": "#ea580c",
  "Planning": "#2563eb",
  "Operations": "#4b5563",
};

export const T = {
  // Backgrounds
  pageBg:    "#f4f6f9",
  sidebar:   "#ffffff",
  card:      "#ffffff",
  cardAlt:   "#f8fafc",
  tableHead: "#f1f5f9",
  tableRow:  "#ffffff",
  tableRowAlt: "#f8fafc",
  tableRowDone: "#f0fdf4",
  tableRowOverdue: "#fff5f5",
  inputBg:   "#f8fafc",
  // Borders
  border:    "#e2e8f0",
  borderMid: "#cbd5e1",
  // Text
  textPrimary: "#0f172a",
  textSecondary: "#475569",
  textMuted: "#94a3b8",
  // Brand
  brand:     "#1e40af",
  brandLight:"#dbeafe",
  // Status
  success:   "#16a34a",
  successBg: "#dcfce7",
  danger:    "#dc2626",
  dangerBg:  "#fee2e2",
  warning:   "#d97706",
  warningBg: "#fef3c7",
  info:      "#0284c7",
  infoBg:    "#e0f2fe",
};